from django.urls import path

from . import views, views_account, views_autore, views_mfa, views_spid, views_verifica

urlpatterns = [
    path("", views.home, name="home"),
    path("segnalazioni/nuova/", views.nuova, name="nuova"),
    path("segnalazioni/<int:pk>/", views.dettaglio, name="dettaglio"),
    path("segnalazioni/<int:pk>/sostieni/", views.sostieni, name="sostieni"),
    path("segnalazioni/<int:pk>/commenta/", views.commenta, name="commenta"),
    path("segnalazioni/<int:pk>/commenti/<int:cid>/elimina/", views.elimina_commento, name="elimina_commento"),
    path("segnalazioni/<int:pk>/modifica/", views_autore.modifica, name="modifica"),
    path("segnalazioni/<int:pk>/elimina/", views_autore.elimina, name="elimina"),
    path("segnalazioni/<int:pk>/revisione/", views_autore.richiedi_revisione_segnalazione, name="revisione_segnalazione"),
    path("profilo/verifiche/<int:vid>/revisione/", views_autore.richiedi_revisione_verifica, name="revisione_verifica"),
    path("api/segnalazioni.geojson", views.geojson, name="geojson"),
    path("api/simili/", views.segnalazioni_simili, name="segnalazioni_simili"),
    path("api/segnalazioni/<int:pk>/sostieni/", views.sostieni_json, name="sostieni_json"),
    path("api/suggerisci-categorie/", views.suggerisci_categorie, name="suggerisci_categorie"),
    path("api/quartiere/", views.quartiere_da_posizione, name="quartiere_da_posizione"),
    path("accedi/", views.accedi, name="accedi"),
    path("accedi/2fa/", views_mfa.secondo_passo, name="accedi_2fa"),
    path("profilo/2fa/", views_mfa.attiva, name="mfa_attiva"),
    path("profilo/2fa/disattiva/", views_mfa.disattiva, name="mfa_disattiva"),
    path("accedi/spid/", views_spid.pagina, name="spid"),
    path("accedi/spid/avvia/<str:metodo>/", views_spid.avvia, name="spid_avvia"),
    path("accedi/spid/ritorno/", views_spid.ritorno, name="spid_ritorno"),
    path("accedi/spid/completa/", views_spid.completa, name="spid_completa"),
    path("esci/", views.esci, name="esci"),
    path("registrati/", views.registrati, name="registrati"),
    path("profilo/", views.profilo, name="profilo"),
    path("profilo/notifiche/", views_account.preferenze_notifica, name="preferenze_notifica"),
    path("profilo/verifica/", views_verifica.riprova, name="riprova_verifica"),
    path("profilo/elimina/", views_account.elimina_account, name="elimina_account"),
    path("profilo/password/", views_account.cambia_password, name="cambia_password"),
    path("profilo/email/", views_account.cambia_email, name="cambia_email"),
    path("profilo/email/conferma/<str:tok>/", views_account.conferma_nuova_email, name="conferma_nuova_email"),
    path("profilo/conferma/", views_account.reinvia_conferma, name="reinvia_conferma"),
    path("conferma-email/<str:tok>/", views_account.conferma_email, name="conferma_email"),
    path("password-dimenticata/", views_account.password_dimenticata, name="password_dimenticata"),
    path("reset-password/<str:tok>/", views_account.reset_password, name="reset_password"),
    path("notifiche/", views.notifiche, name="notifiche"),
    path("normative/", views.pagina_normative, name="normative"),
    path("normative/accetta/", views.accetta_normative, name="accetta_normative"),
    path("statistiche/", views.statistiche, name="statistiche"),
    path("media/<path:path>", views.media_file, name="media"),
]
