# Generated by Django 5.2.17 on 2026-10-06 06:22

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='password_hash', max_length=255, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('codice_fiscale_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('data_nascita', models.DateField()),
                ('metodo_registrazione', models.CharField(max_length=11)),
                ('ruolo', models.CharField(db_default='utente', max_length=14)),
                ('stato_account', models.CharField(db_default='in_attesa_verifica', max_length=18)),
                ('profilo_pubblico', models.BooleanField(db_default=False)),
                ('mfa_attiva', models.BooleanField(db_default=False)),
                ('tentativi_falliti', models.SmallIntegerField(db_default=0)),
                ('bloccato_fino', models.DateTimeField(blank=True, null=True)),
                ('email_verificata_il', models.DateTimeField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('eliminato_il', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utenti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CambioStato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(blank=True, null=True)),
                ('avvenuto_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'cambi_stato',
                'ordering': ['avvenuto_il', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('lista', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'candidati',
                'ordering': ['cognome', 'nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('attiva', models.BooleanField(db_default=True)),
            ],
            options={
                'db_table': 'categorie',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classificazione',
            fields=[
                ('pk', models.CompositePrimaryKey('segnalazione', 'categoria', blank=True, editable=False, primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=10)),
                ('confidenza', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'classificazioni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testo', models.CharField(max_length=1000)),
                ('esito_moderazione', models.CharField(blank=True, max_length=8, null=True)),
                ('punteggio_moderazione', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('nascosto', models.BooleanField(db_default=False)),
                ('motivo_nascosto', models.TextField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('modificato_il', models.DateTimeField(blank=True, null=True)),
                ('eliminato_il', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commenti',
                'ordering': ['creato_il', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consenso',
            fields=[
                ('pk', models.CompositePrimaryKey('utente', 'documento', blank=True, editable=False, primary_key=True, serialize=False)),
                ('accettato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'consensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoNormativo',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('versione', models.CharField(max_length=20)),
                ('testo', models.TextField()),
                ('pubblicato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'documenti_normativi',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inviato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAttivita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avvenuto_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('attore', models.CharField(max_length=7)),
                ('operazione', models.CharField(max_length=30)),
                ('tabella', models.CharField(max_length=50)),
                ('id_oggetto', models.BigIntegerField()),
                ('dati_precedenti', models.JSONField(blank=True, null=True)),
                ('dati_nuovi', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_attivita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=5)),
                ('percorso', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=50)),
                ('dimensione_byte', models.IntegerField()),
                ('durata_sec', models.SmallIntegerField(blank=True, null=True)),
                ('ordine', models.SmallIntegerField()),
                ('copertina', models.BooleanField(db_default=False)),
                ('exif_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('esito_visione', models.CharField(blank=True, max_length=8, null=True)),
                ('punteggio_sessuale', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('punteggio_violenza', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('testo_ocr', models.TextField(blank=True, null=True)),
                ('esito_testo_ocr', models.CharField(blank=True, max_length=8, null=True)),
                ('caricato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'media',
                'ordering': ['ordine'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('messaggio', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('letta', models.BooleanField(db_default=False)),
                ('creata_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'notifiche',
                'ordering': ['-creata_il'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quartiere',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('municipio', models.SmallIntegerField()),
                ('confine', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quartieri',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=8)),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('latitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudine', models.DecimalField(decimal_places=6, max_digits=9)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('esito_moderazione', models.CharField(blank=True, max_length=8, null=True)),
                ('punteggio_moderazione', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('punteggio_coerenza', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('nascosta', models.BooleanField(db_default=False)),
                ('motivo_nascosta', models.TextField(blank=True, null=True)),
                ('creata_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('aggiornata_il', models.DateTimeField(blank=True, null=True)),
                ('eliminata_il', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'segnalazioni',
                'ordering': ['-creata_il'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sostegno',
            fields=[
                ('pk', models.CompositePrimaryKey('utente', 'segnalazione', blank=True, editable=False, primary_key=True, serialize=False)),
                ('creato_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'sostegni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('finale', models.BooleanField()),
                ('pubblico', models.BooleanField()),
            ],
            options={
                'db_table': 'stati',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificaIdentita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tentativo', models.SmallIntegerField()),
                ('tipo_documento', models.CharField(max_length=14)),
                ('ok_lettura_ocr', models.BooleanField()),
                ('ok_corrispondenza_dati', models.BooleanField()),
                ('ok_validita', models.BooleanField()),
                ('ok_autenticita', models.BooleanField()),
                ('ok_confronto_volto', models.BooleanField()),
                ('punteggio', models.SmallIntegerField()),
                ('esito_ia', models.CharField(max_length=11)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('esito_finale', models.CharField(blank=True, max_length=11, null=True)),
                ('motivo_revisione', models.TextField(blank=True, null=True)),
                ('revisionata_il', models.DateTimeField(blank=True, null=True)),
                ('creata_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'verifiche_identita',
                'ordering': ['creata_il'],
                'managed': False,
            },
        ),
    ]
