# Generated by Django 5.2.17 on 2026-10-06 06:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenzaNotifica',
            fields=[
                ('pk', models.CompositePrimaryKey('utente', 'tipo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('in_app', models.BooleanField(db_default=True)),
                ('email', models.BooleanField(db_default=False)),
            ],
            options={
                'db_table': 'preferenze_notifica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RichiestaRevisione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('stato', models.CharField(db_default='aperta', max_length=8)),
                ('risposta', models.TextField(blank=True, null=True)),
                ('creata_il', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'richieste_revisione',
                'ordering': ['creata_il'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sospensione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('inizio', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('revocata_il', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sospensioni',
                'ordering': ['-inizio'],
                'managed': False,
            },
        ),
    ]
